<?php

$DCSignature='drchrono_lionsoft';
$keapTestAppName='yo243';
$keapLiveAppName='';
$keapTestAPIKey='c959c2b28a10eb74a2d5af154ba1986d';
$keapLiveAPIKey='';
$patientTestDataFile='appointment.create.json';
$appointmentTestDataFile='appointment.create.json';
$debugFile='dc2keap.php.dbg';
$appointmentDateFieldName='_AppointmentDate1';
$appointmentTimeFieldName='_AppointmentTime1';
$appointmentLocationFieldName='_AppointmentOfficeLocation';
$drchronoPatientIdFieldName='_PatientChartId';
$timezone='America/Phoenix';
$absPath='C:\Users\JohnBorelli\PhpstormProjects\DrKamranAfzal\oauth.json';
$clientId='fzhAEZhTPOjoO3MpBONt0bPjvveQUwBb86UNW3bc';
$clientSecret='c3lxfc0I76S3Jzz1CEtFpoHgfIU3hWOGsXc24u0yXimR9ZLQruE7xCAYIOLY7FQKkrgl2tybG90IexyvC3UI2xlB4bpdOr2fboGLXCsHNrXAjoG1qD1WtinjSrN2xjg4';