<?php

$DCSignature='drchrono_lionsoft';
$keapTestAppName='yo243';
$keapLiveAppName='nr908';
$keapTestAPIKey='c959c2b28a10eb74a2d5af154ba1986d';
$keapLiveAPIKey='59f28f974c07c0a2e2ec49014e1ee4d5';
$patientTestDataFile='appointment.create.json';
$appointmentTestDataFile='appointment.create.json';
$debugFile='dc2keap.php.dbg';
$appointmentDateFieldName='_AppointmentDate';
$appointmentTimeFieldName='_AppointmentTime';
$appointmentLocationFieldName='_AppointmentOfficeLocation';
$drchronoPatientIdFieldName='_PatientChartId';
$timezone='America/Phoenix';
$absPath='/DrChrono/oauth.json';
$clientId='fzhAEZhTPOjoO3MpBONt0bPjvveQUwBb86UNW3bc';
$clientSecret='c3lxfc0I76S3Jzz1CEtFpoHgfIU3hWOGsXc24u0yXimR9ZLQruE7xCAYIOLY7FQKkrgl2tybG90IexyvC3UI2xlB4bpdOr2fboGLXCsHNrXAjoG1qD1WtinjSrN2xjg4';