<?php

$DCSignature='drchrono secret phrase';
$keapTestAppName='app name';
$keapLiveAppName='';
$keapTestAPIKey='Keap api key here';
$keapLiveAPIKey='';
$patientTestDataFile='appointment.create.json';
$appointmentTestDataFile='appointment.create.json';
$debugFile='dc2keap.php.dbg';
$appointmentDateFieldName='_AppointmentDate1';
$appointmentTimeFieldName='_AppointmentTime1';
$appointmentLocationFieldName='_AppointmentOfficeLocation';
$drchronoPatientIdFieldName='_PatientChartId';
$timezone='America/Phoenix';
$absPath='C:\Users\JohnBorelli\PhpstormProjects\DrKamranAfzal\oauth.json';
$clientId='your client id';
$clientSecret='your client secret';
